name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2020-historic
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:

      - name: Clone the reference repository
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --no-cache-dir -U -r requirements.txt | cat
          python -m pip install pytest pytest-cov coveralls setuptools
          python -m pip install -e .
      
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          pytest -v --cov=probml_utils --cov-report term-missing
          coveralls --service=github

  coveralls:
    name: Finish coverage
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
