name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: texlive/texlive:TL2020-historic
    steps:

      - name: Clone the reference repository
        uses: actions/checkout@v2

      - name: Install python and pip
        run: |
          apt update
          apt install python3-pip -y

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -U -r requirements-dev.txt | cat
          pip install --no-cache-dir -U -r requirements-extra.txt | cat
          pip install -e .
          pip install pytest pytest-cov coveralls
      
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
        run: |
          pytest -v --cov=probml_utils --cov-report term-missing
          coveralls --service=github

  coveralls:
    name: Finish coverage
    needs: test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Finished
      run: |
        pip3 install --upgrade coveralls
        coveralls --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
